spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockpulse
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  jwt:
    secret: "Y0urSuperSecureKeyShouldBe64CharactersMinimumLong123!"

server:
  port: 8080
